---
title: "Constructors for Pipeline Stages"
execute:
  freeze: true
---

```{r, eval=ecodown::examples_not_run()}
#| include: false
options("pillar.width" = 60)
library(sparklyr) 
library(dplyr)
```

*R/ml_transformer_and_estimator.R*

## ml-constructors

## Description
Functions for developers writing extensions for Spark ML. 


## Usage
```r
new_ml_transformer(jobj, ..., class = character()) 

new_ml_prediction_model(jobj, ..., class = character()) 

new_ml_classification_model(jobj, ..., class = character()) 

new_ml_probabilistic_classification_model(jobj, ..., class = character()) 

new_ml_clustering_model(jobj, ..., class = character()) 

new_ml_estimator(jobj, ..., class = character()) 

new_ml_predictor(jobj, ..., class = character()) 

new_ml_classifier(jobj, ..., class = character()) 

new_ml_probabilistic_classifier(jobj, ..., class = character()) 
```

## Arguments
|Arguments|Description|
|---|---|
| jobj | Pointer to the pipeline stage object. |
| ... | (Optional) additional attributes of the object. |
| class | Name of class. |








```{r, eval=ecodown::examples_not_run()}
#| include: false
spark_disconnect_all()
```
