---
title: "Additional Resources"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
---

## Demos and Presentations

<br/>

### R & Spark - How to Analyze Data Using RStudio’s sparkly 

Demo and presentation by Nathan Stephen at the 2017 Spark Summit

<iframe width="510" height="340" src="https://www.youtube.com/embed/oItFZfzqqMY" frameborder="0" allowfullscreen></iframe>

<br/>

<h3> <a href="https://github.com/rstudio/sparkDemos/tree/master/prod/presentations/cloudera">
Analyzing Hadoop Data Using sparklyr  </a> </h3>

Source code of the examples used in the web demo showing how to use spaklyr to analyze 1.1 Billion records using sparklyr and Cloudera.  

Link to the video at cloudera.com - <a href="https://www.cloudera.com/content/dam/www/marketing/resources/webinars/analyzing-hadoop-data-using-sparklyr-recorded-webinar.png.landing.html"> Analyzing Hadoop with sparklyr </a>

<br/>

<h3> <a href="https://github.com/rstudio/rstudio-conf/tree/master/2017/R_and_Spark_Javier_Luraschi" >
R and Spark </a>  </h3>

<script src="//fast.wistia.com/assets/external/E-v1.js" async></script>
<div class="wistia_responsive_padding" style="padding:40% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:80%;left:0;position:absolute;top:0;width:70%;"><div class="wistia_embed wistia_async_trit8aqxmn videoFoam=true" style="height:50%;width:50%">&nbsp;</div></div></div>

Video and materials of Javier Luraschi's presentation delivered during the RStudio Conference 2017. It shows how to sample 1 trillion pages using sparklyr to answer the question: What is the most used keyword or library in the web?

Link to the Presentation Deck - <a href="https://beta.rstudioconnect.com/content/2371/r-and-spark.html"> R and Spark </a>

Link to the RPubs article - <a href="http://rpubs.com/jluraschi/billion-tags"> Analyzing 4 Billions of Tags with R and Spark </a>

<br/>

## Blog Posts

<br/>

<h3> <a href="https://blog.rstudio.org/2017/01/24/sparklyr-0-5/">
sparklyr 0.5 </a> </h3>

Announcement regarding the release of sparklyr 0.5 into CRAN.  This article expands on the newest features in sparklyr.

<br/>

<h3> <a href="http://blog.cloudera.com/blog/2016/12/automating-your-sparklyr-environment-with-cloudera-director/">
How-to: Automate Your sparklyr Environment with Cloudera Director  </a> </h3>

Post in the Cloudera Engineering Blog that shows how to automate a sparklyr environment on AWS using Cloudera Director






