---
title: "Site News"
format:
  html:
    theme: default
    toc: true
execute:
  freeze: true
---

+-----------+-------------+-------------------------------------------------------------------+
| Date      | Event       | Article / Page                                                    |
+===========+=============+===================================================================+
| 8/31/22   | Updated     | [Understanding Spark Caching](/guides/caching.qmd)                |
+-----------+-------------+-------------------------------------------------------------------+
| 3/2/22    | Newly added | [`tidymodels` with Spark](/guides/tidymodels.qmd)                 |
+-----------+-------------+-------------------------------------------------------------------+
| 1/25/22   | Newly added | [Get Started - Model Data](/get-started/model-data.qmd)           |
+-----------+-------------+-------------------------------------------------------------------+
| 1/25/22   | Newly added | [Get Started - Prepare Data](/get-started/prepare-data.qmd)       |
+-----------+-------------+-------------------------------------------------------------------+
| 1/25/22   | Updated     | [Spark Machine Learning Library (MLlib)](/guides/mlib.qmd)        |
+-----------+-------------+-------------------------------------------------------------------+
| 1/25/22   | Updated     | [Manipulating Data with `dplyr`](/guides/dplyr.qmd)               |
+-----------+-------------+-------------------------------------------------------------------+
| 1/24/22   | Newly added | [Get Started - Read Data](/get-started/read-data.qmd)             |
+-----------+-------------+-------------------------------------------------------------------+
| 1/24/22   | Newly added | [Get Started - Install](/get-started/index.qmd)                   |
+-----------+-------------+-------------------------------------------------------------------+
| 1/21/22   | Updated     | [Distributing R Computations](/guides/distributed-r.qmd)          |
+-----------+-------------+-------------------------------------------------------------------+
| 1/21/22   | Updated     | [Intro to Spark Streaming with `sparklyr`](/guides/streaming.qmd) |
+-----------+-------------+-------------------------------------------------------------------+
| 1/20/22   | Updated     | [Text mining with Spark & `sparklyr`](/guides/textmining.qmd)     |
+-----------+-------------+-------------------------------------------------------------------+
| 1/20/22   | Updated     | [Spark ML Pipelines](/guides/pipelines.qmd)                       |
+-----------+-------------+-------------------------------------------------------------------+
