---
title: "Deploys Databricks backed content to publishing server"
execute:
  eval: true
  freeze: true
---

## deploy_databricks

## Description
This is a convenience function that is meant to make it easier for you to publish your Databricks backed content to a publishing server. It is meant to be primarily used with Posit Connect.


## Usage
```r
deploy_databricks(
  appDir = NULL,
  python = NULL,
  account = NULL,
  server = NULL,
  lint = FALSE,
  forceGeneratePythonEnvironment = TRUE,
  version = NULL,
  cluster_id = NULL,
  host = NULL,
  token = NULL,
  confirm = interactive(),
  ...
)
```

## Arguments
|Arguments|Description|
|---|---|
| appDir | A directory containing an application (e.g. a Shiny app or plumber API) Defaults to NULL. If left NULL, and if called within RStudio, it will attempt to use the folder of the currently opened document within the IDE. If there are no opened documents, or not working in the RStudio IDE, then it will use `getwd()` as the default value. |
| python | Full path to a python binary for use by `reticulate.` It defaults to NULL. If left NULL, this function will attempt to find a viable local Python environment to replicate using the following hierarchy:         1. `version` - Cluster's DBR version         2. `cluster_id` - Query the cluster to obtain its DBR version         3. If one is loaded in the current R session, it will verify           that the Python environment is suited to be used as the one           to use  |
| account | The name of the account to use to publish |
| server | The name of the target server to publish |
| lint | Lint the project before initiating the project? Default to FALSE. It has been causing issues for this type of content. |
| forceGeneratePythonEnvironment | If an existing requirements.txt file is found, it will be overwritten when this argument is TRUE. |
| version | The Databricks Runtime (DBR) version. Use if `python` is NULL. |
| cluster_id | The Databricks cluster ID. Use if `python`, and `version` are NULL |
| host | The Databricks host URL. Defaults to NULL. If left NULL, it will use the environment variable `DATABRICKS_HOST` |
| token | The Databricks authentication token. Defaults to NULL. If left NULL, it will use the environment variable `DATABRICKS_TOKEN` |
| confirm | Should the user be prompted to confirm that the correct information is being used for deployment? Defaults to `interactive()` |
| ... | Additional named arguments passed to `rsconnect::deployApp()` function |


## Value
No value is returned to R. Only output to the console.






