---
title: mleap
description: Interface to 'MLeap'
---
Function(s) | Description
|---|---|
|[install_maven()](/packages/mleap/reference/install_maven.html)|Install Maven|
|[install_mleap()](/packages/mleap/reference/install_mleap.html)|Install MLeap runtime|
|[ml_read_bundle()](/packages/mleap/reference/ml_read_bundle.html)|Loads an MLeap bundle into Spark|
|[ml_write_bundle()](/packages/mleap/reference/ml_write_bundle.html)|Export a Spark pipeline for serving|
|[ml_write_to_bundle_transformed()](/packages/mleap/reference/ml_write_to_bundle_transformed.html)|Export a Spark pipeline for serving|
|[mleap_dependency_versions()](/packages/mleap/reference/mleap_dependency_versions.html)|A table containing the combinations of Spark, Scala and MLeap versions to use|
|[mleap_installed_versions()](/packages/mleap/reference/mleap_installed_versions.html)|Find existing MLeap installations|
|[mleap_load_bundle()](/packages/mleap/reference/mleap_load_bundle.html)|Loads an MLeap bundle|
|[mleap_model_schema()](/packages/mleap/reference/mleap_model_schema.html)|MLeap model schema|
|[mleap_transform()](/packages/mleap/reference/mleap_transform.html)|Transform data using an MLeap model|
