---
title: Package index
toc: false
---

[gf_bfs()](gf_bfs.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Breadth-first search (BFS)

[gf_cache()](gf_cache.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cache the GraphFrame

[gf_chain()](gf_chain.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Chain graph

[gf_connected_components()](gf_connected_components.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Connected components

[gf_degrees()](gf_degrees.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Degrees of vertices

[gf_edge_columns()](gf_edge_columns.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Edges column names

[gf_edges()](gf_edges.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Extract edges DataFrame

[gf_find()](gf_find.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Motif finding: Searching the graph for structural patterns

[gf_friends()](gf_friends.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Graph of friends in a social network.

[gf_graphframe()](gf_graphframe.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Create a new GraphFrame

[gf_grid_ising_model()](gf_grid_ising_model.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Generate a grid Ising model with random parameters

[gf_in_degrees()](gf_in_degrees.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In-degrees of vertices

[gf_lpa()](gf_lpa.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Label propagation algorithm (LPA)

[gf_out_degrees()](gf_out_degrees.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Out-degrees of vertices

[gf_pagerank()](gf_pagerank.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;PageRank

[gf_persist()](gf_persist.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Persist the GraphFrame

[gf_register()](gf_register.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Register a GraphFrame object

[gf_scc()](gf_scc.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Strongly connected components

[gf_shortest_paths()](gf_shortest_paths.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shortest paths

[gf_star()](gf_star.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Generate a star graph

[gf_triangle_count()](gf_triangle_count.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Computes the number of triangles passing through each vertex.

[gf_triplets()](gf_triplets.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Triplets of graph

[gf_two_blobs()](gf_two_blobs.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Generate two blobs

[gf_unpersist()](gf_unpersist.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Unpersist the GraphFrame

[gf_vertex_columns()](gf_vertex_columns.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Vertices column names

[gf_vertices()](gf_vertices.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Extract vertices DataFrame

[spark_graphframe()](spark_graphframe.qmd)


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Retrieve a GraphFrame

