---
title: pysparklyr
description: Provides a 'PySpark' Back-End for the 'sparklyr' Package
---
Function(s) | Description
|---|---|
|[connection_databricks_shinyapp()](/packages/pysparklyr/latest/reference/connection_databricks_shinyapp.html)|A Shiny app that can be used to construct a <code>spark_connect</code> statement|
|[deploy_databricks()](/packages/pysparklyr/latest/reference/deploy_databricks.html)|Deploys Databricks backed content to publishing server|
|[install_pyspark() install_databricks()](/packages/pysparklyr/latest/reference/install_pyspark.html)|Installs PySpark and Python dependencies|
|[installed_components()](/packages/pysparklyr/latest/reference/installed_components.html)|Lists installed Python libraries|
|[ml_prepare_dataset()](/packages/pysparklyr/latest/reference/ml_prepare_dataset.html)|Creates the 'label' and 'features' columns|
|[`%>%`](/packages/pysparklyr/latest/reference/pipe.html)|Pipe operator|
|[requirements_write()](/packages/pysparklyr/latest/reference/requirements_write.html)|Writes the 'requirements.txt' file, containing the needed Python libraries|
|[spark_connect_service_start() spark_connect_service_stop()](/packages/pysparklyr/latest/reference/spark_connect_service_start.html)|Starts and stops Spark Connect locally|
