---
title: "Create a new GraphFrame"
execute:
  freeze: true
---

```{r, eval=ecodown::examples_not_run()}
#| include: false
options("pillar.width" = 60)
library(sparklyr) 
library(dplyr)
```

*R/gf_interface.R*

## gf_graphframe

## Description
 Create a new GraphFrame 


## Usage
```r
 
gf_graphframe(vertices = NULL, edges) 
```

## Arguments
|Arguments|Description|
|---|---|
| vertices | A `tbl_spark` representing vertices. |
| edges | A `tbl_psark` representing edges. |





## Examples
```{r, eval=ecodown::examples_run()}
library(graphframes)
 
```
```{r, eval=ecodown::examples_not_run()}
library(graphframes)
 
library(sparklyr) 
sc <- spark_connect(master = "local", version = "2.3.0") 
v_tbl <- sdf_copy_to( 
  sc, data.frame(id = 1:3, name = LETTERS[1:3]) 
) 
e_tbl <- sdf_copy_to( 
  sc, data.frame(src = c(1, 2, 2), dst = c(2, 1, 3), 
                 action = c("love", "hate", "follow")) 
) 
gf_graphframe(v_tbl, e_tbl) 
gf_graphframe(edges = e_tbl) 
 
```



```{r, eval=ecodown::examples_not_run()}
#| include: false
spark_disconnect_all()
```
