---
title: graphframes
description: Interface for 'GraphFrames'
---
Function(s) | Description
|---|---|
|[gf_bfs()](/packages/graphframes/latest/reference/gf_bfs.html)|Breadth-first search (BFS)|
|[gf_cache()](/packages/graphframes/latest/reference/gf_cache.html)|Cache the GraphFrame|
|[gf_chain()](/packages/graphframes/latest/reference/gf_chain.html)|Chain graph|
|[gf_connected_components()](/packages/graphframes/latest/reference/gf_connected_components.html)|Connected components|
|[gf_degrees()](/packages/graphframes/latest/reference/gf_degrees.html)|Degrees of vertices|
|[gf_edge_columns()](/packages/graphframes/latest/reference/gf_edge_columns.html)|Edges column names|
|[gf_edges()](/packages/graphframes/latest/reference/gf_edges.html)|Extract edges DataFrame|
|[gf_find()](/packages/graphframes/latest/reference/gf_find.html)|Motif finding: Searching the graph for structural patterns|
|[gf_friends()](/packages/graphframes/latest/reference/gf_friends.html)|Graph of friends in a social network.|
|[gf_graphframe()](/packages/graphframes/latest/reference/gf_graphframe.html)|Create a new GraphFrame|
|[gf_grid_ising_model()](/packages/graphframes/latest/reference/gf_grid_ising_model.html)|Generate a grid Ising model with random parameters|
|[gf_in_degrees()](/packages/graphframes/latest/reference/gf_in_degrees.html)|In-degrees of vertices|
|[gf_lpa()](/packages/graphframes/latest/reference/gf_lpa.html)|Label propagation algorithm (LPA)|
|[gf_out_degrees()](/packages/graphframes/latest/reference/gf_out_degrees.html)|Out-degrees of vertices|
|[gf_pagerank()](/packages/graphframes/latest/reference/gf_pagerank.html)|PageRank|
|[gf_persist()](/packages/graphframes/latest/reference/gf_persist.html)|Persist the GraphFrame|
|[gf_register()](/packages/graphframes/latest/reference/gf_register.html)|Register a GraphFrame object|
|[gf_scc()](/packages/graphframes/latest/reference/gf_scc.html)|Strongly connected components|
|[gf_shortest_paths()](/packages/graphframes/latest/reference/gf_shortest_paths.html)|Shortest paths|
|[gf_star()](/packages/graphframes/latest/reference/gf_star.html)|Generate a star graph|
|[gf_triangle_count()](/packages/graphframes/latest/reference/gf_triangle_count.html)|Computes the number of triangles passing through each vertex.|
|[gf_triplets()](/packages/graphframes/latest/reference/gf_triplets.html)|Triplets of graph|
|[gf_two_blobs()](/packages/graphframes/latest/reference/gf_two_blobs.html)|Generate two blobs|
|[gf_unpersist()](/packages/graphframes/latest/reference/gf_unpersist.html)|Unpersist the GraphFrame|
|[gf_vertex_columns()](/packages/graphframes/latest/reference/gf_vertex_columns.html)|Vertices column names|
|[gf_vertices()](/packages/graphframes/latest/reference/gf_vertices.html)|Extract vertices DataFrame|
|[spark_graphframe() spark_graphframe()](/packages/graphframes/latest/reference/spark_graphframe.html)|Retrieve a GraphFrame|
