baseurl = "/"
languageCode = "en-us"
title = "sparklyr"
theme = "rstudio-docs-theme"
metadataformat = "yaml"
pluralizeListTitles =   "false"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
canonifyurls = true
googleAnalytics = "UA-20375833-3"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

[params]
    description = "An R interface to Spark"
    copyright = "Copyright 2017, RStudio, Inc."
	  repo = "https://github.com/rstudio/sparklyr"
	  logo = "favicon.png"

[[menu.main]]
    weight = 1
    name = "Using sparklyr"

[[menu.main]]
    weight = 2
    name = "Configuring connections"
    parent = "Using sparklyr"
    url = "/guides/connections/"

[[menu.main]]
    weight = 3
    name = "Troubleshooting"
    parent = "Using sparklyr"
    url = "/troubleshooting/"

[[menu.main]]
    weight = 10
    name = "Guides"

[[menu.main]]
    weight = 11
    name = "Manipulating data"
    parent = "Guides"
    url = "/dplyr/"

[[menu.main]]
    weight = 12
    name = "Machine Learning"
    parent = "Guides"
    url = "/mlib/"

[[menu.main]]
    weight = 13
    name = "Understanding Caching"
    parent = "Guides"
    url = "/guides/caching/"

[[menu.main]]
    weight = 14
    name = "Deployment Options"
    parent = "Guides"
    url = "/deployment/"

[[menu.main]]
    weight = 15
    name = "Distributed R"
    parent = "Guides"
    url = "/guides/distributed-r/"

[[menu.main]]
    weight = 16
    name = "Data Lakes"
    parent = "Guides"
    url = "/guides/data-lakes/"

[[menu.main]]
    weight = 17
    name = "ML Pipelines"
    parent = "Guides"
    url = "/guides/pipelines"

[[menu.main]]
    weight = 18
    name = "Text mining"
    parent = "Guides"
    url = "/guides/textmining"

[[menu.main]]
    weight = 19
    name = "Stream Analysis"
    parent = "Guides"
    url = "/guides/streaming"

[[menu.main]]
    weight = 20
    name = "Apache Arrow"
    parent = "Guides"
    url = "/guides/arrow/"

[[menu.main]]
    weight = 20
    name = "AWS S3 buckets"
    parent = "Guides"
    url = "/guides/aws-s3/"

[[menu.main]]
    weight = 30
    name = "Extend sparklyr"
    url = "/extensions/"

[[menu.main]]
    weight = 31
    name = "Using H2O"
    parent = "Extend sparklyr"
    url = "/guides/H2O"

[[menu.main]]
    weight = 32
    name = "Graph Analysis"
    parent = "Extend sparklyr"
    url = "/graphframes"

[[menu.main]]
    weight = 33
    name = "Production pipelines"
    parent = "Extend sparklyr"
    url = "/guides/mleap"

[[menu.main]]
    weight = 50
    name = "Deployment Examples"
    url = "/examples/"

[[menu.main]]
    weight = 51
    name = "Standalone cluster"
    parent = "Deployment Examples"
    url = "/examples/stand-alone-aws/"

[[menu.main]]
    weight = 52
    name = "YARN cluster"
    parent = "Deployment Examples"
    url = "/examples/yarn-cluster-emr/"

[[menu.main]]
    weight = 53
    name = "Cloudera cluster"
    parent = "Deployment Examples"
    url = "/examples/cloudera-aws/"

[[menu.main]]
    weight = 54
    name = "Databricks cluster"
    parent = "Deployment Examples"
    url = "/examples/databricks-cluster/"
    
[[menu.main]]
    weight = 55
    name = "Qubole cluster"
    parent = "Deployment Examples"
    url = "/examples/qubole-overview/"

[[menu.main]]
    weight = 60
    name = "Reference"
    url = "/reference/"
