---
title: "Guides"
---

::: {layout-ncol="2"}
::: {style="display: block;"}
### Interacting with Spark

- [Using `dplyr` commands](/guides/dplyr.qmd)  
- [Understanding Spark Caching](/guides/caching.qmd)
- [Spark connection options](/guides/connections.qmd) 
- [Access AWS S3 Buckets](/guides/aws-s3.qmd)
:::
::: {style="display: block;"}
### Spark Machine Learning

- [Spark ML Overview](/guides/mlib.qmd)
- [ML Pipelines](/guides/pipelines.qmd)
- [Text Modeling](/guides/textmodeling.qmd)
- [Model Tuning](/guides/model_tuning.qmd)
- [Grid Search Tuning](/guides/model_tuning_text.qmd)
- [Using H2O in `sparklyr`](/guides/h2o.qmd)

### Tidymodels in Spark

- [Using `tidymodels` (basics)](/guides/tidymodels.qmd)
- [Tune `tidymodels` remotely in Spark Connect](/guides/tune_tidymodels_spark.qmd)
:::
:::

::: {layout-ncol="2"}
::: {style="display: block;"}
### Non-rectangular Data

- [Stream Data](/guides/streaming.qmd)
- [Text Mining](/guides/textmining.qmd)

:::
::: {style="display: block;"}
### Advanced

- [Run R code in Spark](/guides/distributed-r.qmd)
- [Create `sparklyr` extensions](/guides/extensions.qmd)
:::
:::

