---
title: "Troubleshooting"
format:
  html:
    theme: default
    toc: true
---

## Help with code debugging

For general programming questions with `sparklyr`, please ask on [Stack Overflow](http://stackoverflow.com).  

## Code does not work after upgrading to the latest `sparklyr` version

Please refer to the [NEWS](/news) section of the `sparklyr` package to find out if any of the updates listed may have changed the way your code needs to work. 

If it seems that current version of the package has a bug, or the new functionality does not perform as stated, please refer to the `sparklyr` [ISSUES](https://github.com/rstudio/sparklyr/issues) page.  If no existing issue matches to what your problem is, please open a new issue.

## Not able to connect, or the jobs take a long time when working with a Data Lake

The [Configuration connections](/guides/connections) contains an overview and recommendations for requesting resources form the cluster.

The articles in the **Guides** section provide best-practice information about specific operations that may match to the intent of your code. 

To verify your infrastructure, please review the **Deployment Examples** section.