on:
  push:
    branches: site
  pull_request:
    branches: site

name: Build Site

jobs:
  ecodown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@main
        with:
          version: 0.9.208

      - name: Install pkgdepends
        run: install.packages("pkgdepends")
        shell: Rscript {0}

      - name: Install pak
        run: install.packages("pak")
        shell: Rscript {0}

      - name: Install ecodown
        run: pak::pkg_install("edgararuiz/ecodown")
        shell: Rscript {0}
        
      - name: Install ecodown's deps
        run: pak::pkg_system_requirements("ecodown", "ubuntu", "20.04")
        shell: Rscript {0}     
        
      - name: Build site
        run: ecodown::ecodown_build()
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: site
          folder: docs